spring.application.name=studydocs

spring.config.import=optional:file:./secrets/postgresql.properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true